#kafka endpoint
kafka:
  bootstrapAddress: localhost:9092

#Topic de test
test:
  topic:
    name: kafka-topic-json

#Spring profiles
spring:
  profiles:
    active: prod


  kafka:
    consumer:
      properties:
        spring:
          json:
            trusted:
              packages: ch.globaz.devsecops.common