#kafka endpoint
kafka:
  bootstrapAddress: localhost:9092

#Topic
  topic:
    test:
      name: kafka-topic-json
      consumer-group:
        name: kafka-topic-group

#Spring profiles
spring:
  profiles:
    active:

