#kafka endpoint
kafka:
  bootstrapAddress: 10.128.20.110:9092

#Topic de test
test:
  topic:
    name: kafka-topic-json2
  retry:
    topic:
      name: kafka-topic-json2-retry

#Spring profiles
spring:
  profiles:
    active:
